# 使用说明 V3.0.0
# 1. 使用docker-compose  宿主机不需要配置host来发现
# 2. 无需修改源码，根目录  docker-compose up 即可
# 3. 静静等待服务启动

version: '3'
services:
  xs-api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 9525:9525
    restart: always
    image: xs-api
    container_name: xs-api
#    network_mode: host
#  xs-mqtt:
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#    ports:
#      - 9525:9525
#    restart: always
#    image: xs-api
#    container_name: xs-api



